### PR TITLE
Sample graphql lookup of related records

### PR DESCRIPTION
**Pull request by AdamLiechty**
This is an example for the [GraphQL Wire Adapters and Functions Pilot](https://developer.salesforce.com/docs/component-library/documentation/en/lwc/lwc.reference_lightning_graphql_api)

This example focuses on a new `accountRelatedContacts` sample component.

It `@wire`s `graphql` to run a primable query to fetch the top 5 related Contacts.

For completeness, a simple viewContactRecord LWC is proveded, so that tapping a Contact in the list can navigate to view the Contact.

### CODE REVIEW

**Comment by dbreese** [comment]
When I attempt to deploy, I get the following error - I imagine it is related to our org setup? 

```
=== Deploy Errors
PROJECT PATH  ERRORS                                                                                                                                                                   
────────────  ─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
              Validation error of type UnknownArgument: Unknown field argument name @ 'uiapi/query/Account/edges/node/Contacts/edges/node/Phone'. line: 16, column: 41, startIndex: 556
              Validation error of type UnknownArgument: Unknown field argument name @ 'uiapi/query/Account/edges/node/Contacts/edges/node/Name'. line: 13, column: 40, startIndex: 435 
              Validation error of type UnknownArgument: Unknown field argument name @ 'uiapi/query/Account'. line: 6, column: 25, startIndex: 168                                      
              Validation error of type UnknownDirective: Unknown directive category @ 'uiapi/query/Account/edges/node/Contacts/edges/node/Name'. line: 13, column: 30, startIndex: 425 
              Validation error of type UnknownDirective: Unknown directive category @ 'uiapi/query/Account/edges/node/Contacts/edges/node/Phone'. line: 16, column: 31, startIndex: 546
              Validation error of type UnknownDirective: Unknown directive category @ 'uiapi/query/Account/edges/node/Contacts'. line: 9, column: 38, startIndex: 273                  
              Validation error of type UnknownDirective: Unknown directive category @ 'uiapi/query/Account'. line: 6, column: 15, startIndex: 158                                      
              Validation error of type UnknownArgument: Unknown field argument name @ 'uiapi/query/Account/edges/node/Contacts/edges/node/Email'. line: 19, column: 41, startIndex: 677
              Validation error of type UnknownDirective: Unknown directive category @ 'uiapi/query/Account/edges/node/Contacts/edges/node/Email'. line: 19, column: 31, startIndex: 667
              Validation error of type UnknownArgument: Unknown field argument name @ 'uiapi/query/Account/edges/node/Contacts'. line: 9, column: 48, startIndex: 283                  

09:07:05.557 ended SFDX: Deploy Source to Org

```

**Comment by AdamLiechty** [comment]
@dbreese I'm seeing the same all of a sudden. Looking.

**Comment by dbreese** [comment]
Just checking in, are you still seeing the issue @AdamLiechty ?

**Comment by AdamLiechty** [comment]
@dbreese I no longer see this issue

**Comment by dbreese** [comment]
I'm seeing the same linting error with node 14:

```
% volta install node@14
% npm install
% npm run lint
```

```
TypeError: Error while loading rule '@salesforce/lwc-graph-analyzer/no-undefined-wire-config-property': Cannot read property '1' of undefined
Occurred while linting /Users/dbreese/dev/offline-app-developer-starter-kit/force-app/main/default/lwc/accountRelatedContacts/accountRelatedContacts.js/0_/Users/dbreese/dev/offline-app-developer-starter-kit/force-app/main/default/lwc/accountRelatedContacts/accountRelatedContacts.js/0_/Users/dbreese/dev/offline-app-developer-starter-kit/force-app/main/default/lwc/accountRelatedContacts/accountRelatedContacts.js/0_/Users/dbreese/dev/offline-app-developer-starter-kit/force-app/main/default/lwc/accountRelatedContacts/accountRelatedContacts.js
    at /Users/dbreese/dev/offline-app-developer-starter-kit/node_modules/@salesforce/eslint-plugin-lwc-graph-analyzer/lib/util/helper.js:94:59
```

**Comment by dbreese** [comment]
Oh, and same issue with node 16.

**Pull request closed without merging**
