### PR TITLE
Adding UX suggestions.

### PR DESCRIPTION
**Pull request by dbreese**
Attempting to get closer to UX suggestions. The record name/object type still looks off to me, but the icon is 32x32 and font size is 14pt.

Updated screen shots showing changes in Test Harness: 

Screenshot 2023-04-07 at 3 48 49 PM
Screenshot 2023-04-07 at 3 49 08 PM

@khawkins @AdamLiechty

### CODE REVIEW

**Review by maliroteh-sf — APPROVED** [review]

**Review by khawkins — APPROVED** [review]

**Comment by dbreese** [comment]
Hold off on merging, reviewing with UX to make sure font sizes are ok.

**Comment by khawkins** [comment]
> Hold off on merging, reviewing with UX to make sure font sizes are ok.

Per our process, we need to hold off until Q3 signs off as well.

**Comment by dbreese** [comment]
Good, and it looks like more changes are needed. Meeting with UX to figure out what else meeds to be done.

**Comment by apaschapur** [comment]
Q3 team tested and issue W-13060500 was filed while testing these changes https://gus.lightning.force.com/lightning/r/ADM_Work__c/a07EE00001PkortYAB/view

**Comment by dbreese** [comment]
Sorry @apaschapur - the PR is not ready yet per my comments above. I've already fixed the SAVE button issue and will mark the bug you created as fixed when I'm done working with UX on other changes.

**Comment by khawkins** [comment]
Can we take internal WI references and links out of comments here? This is a public repository.

**Comment by dbreese** [comment]
@apaschapur The PR has been updated with UX suggestions and is ready to be tested and merged. Can Q3 team please retest?

**Comment by apaschapur** [comment]
@dbreese we tested the changes on both platforms and it looks good 👍

**Pull request merged**
