### PR TITLE
Update dependency versions

### PR DESCRIPTION
**Pull request by sfdctaka**

### CODE REVIEW

**Review by maliroteh-sf — APPROVED** [review]
LGTM but please set up your signing key to sign your commits in the future.

**Comment by sfdctaka** [comment]
My commit is signed I believe. I used `git log --show-signature` to check. Can you tell me how you checked it so I can see it too?

**Comment by khawkins** [comment]
> My commit is signed I believe. I used `git log --show-signature` to check. Can you tell me how you checked it so I can see it too?

You signed it, but you haven't uploaded your GPG key to your account settings in GitHub, would be my guess:
image

**Review by khawkins — APPROVED** [review]

**Comment by sfdctaka** [comment]
image

😄

**Pull request merged**
